const state={apiBase:'https://magicpin-vera-chat-bot.onrender.com',demoLoaded:false};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2600)}
function apiUrl(path){return state.apiBase.replace(/\/$/,'')+path}
async function request(path,options={}){const r=await fetch(apiUrl(path),{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json();if(!r.ok)throw new Error(data.reason||data.detail||`HTTP ${r.status}`);return data}
function setApi(ok,text){const c=$('#apiChip');c.classList.toggle('ok',ok);$('#apiText').textContent=text;$('#healthStatus').textContent=ok?'Healthy':'Unavailable';$('#healthStatus').style.color=ok?'#16a36a':'#d85d73'}
async function health(){try{const d=await request('/v1/healthz');setApi(true,`Backend healthy · ${d.contexts_loaded?.merchant||0} merchants`);toast('Backend is reachable.')}catch(e){setApi(false,'Backend unavailable');toast(`Backend check failed: ${e.message}`)}}
const demoCategory={slug:'dentists',display_name:'Dentists',voice:{tone:'peer_clinical',register:'respectful_collegial',code_mix:'hindi_english_natural',vocab_allowed:['fluoride varnish','scaling','caries','aligner'],vocab_taboo:['guaranteed','100% safe','miracle']},offer_catalog:[{id:'den_001',title:'Dental Cleaning @ ₹299',value:'299',audience:'new_user',type:'service_at_price'}],peer_stats:{avg_rating:4.4,avg_ctr:.03},digest:[{id:'d_2026W17_jida_fluoride',kind:'research',title:'3-month fluoride varnish recall outperforms 6-month for high-risk adult caries',source:'JIDA Oct 2026, p.14',trial_n:2100,patient_segment:'high_risk_adults',summary:'Multi-center Indian trial shows 38% lower caries recurrence with 3-month vs 6-month recall in adults with active decay history.'}]};
const demoMerchant={merchant_id:'m_001_drmeera_dentist_delhi',category_slug:'dentists',identity:{name:"Dr. Meera's Dental Clinic",city:'Delhi',locality:'Lajpat Nagar',verified:true,languages:['en','hi'],owner_first_name:'Meera'},subscription:{status:'active',plan:'Pro',days_remaining:82},performance:{window_days:30,views:2410,calls:18,directions:45,ctr:.021,leads:9,delta_7d:{views_pct:.18,calls_pct:-.05,ctr_pct:.02}},offers:[{id:'o_meera_001',title:'Dental Cleaning @ ₹299',status:'active',started:'2026-03-01'}],conversation_history:[{ts:'2026-04-24T10:12:00Z',from:'vera',body:'Profile audit done — your photos are 8/10, description complete, but Google posts are stale (last post 22 days ago).',engagement:'merchant_replied'},{ts:'2026-04-24T10:18:00Z',from:'merchant',body:'Yes please, focus on whitening and aligners',engagement:'intent_action'}],customer_aggregate:{total_unique_ytd:540,lapsed_180d_plus:78,retention_6mo_pct:.38,high_risk_adult_count:124},signals:['stale_posts:22d','ctr_below_peer_median','high_risk_adult_cohort','engaged_in_last_48h']};
const demoTrigger={id:'trg_001_research_digest_dentists',scope:'merchant',kind:'research_digest',source:'external',merchant_id:'m_001_drmeera_dentist_delhi',customer_id:null,payload:{category:'dentists',top_item_id:'d_2026W17_jida_fluoride'},urgency:2,suppression_key:'research:dentists:2026-W17',expires_at:'2026-05-03T00:00:00Z'};
const demoCustomer={customer_id:'c_001_priya_for_m001',merchant_id:'m_001_drmeera_dentist_delhi',identity:{name:'Priya',language_pref:'hi-en mix'},relationship:{last_visit:'2026-05-12',visits_total:4,lifetime_value:1696},state:'lapsed_soft',preferences:{preferred_slots:'weekday_evening',channel:'whatsapp',reminder_opt_in:true},consent:{scope:['recall_reminders','appointment_reminders']}};
async function push(scope,id,payload,version=1){return request('/v1/context',{method:'POST',body:JSON.stringify({scope,context_id:id,version,payload,delivered_at:new Date().toISOString()})})}
async function loadDemo(){try{await push('category','dentists',demoCategory);await push('merchant',demoMerchant.merchant_id,demoMerchant);await push('trigger',demoTrigger.id,demoTrigger);await push('customer',demoCustomer.customer_id,demoCustomer);state.demoLoaded=true;toast('Demo context loaded into Vera.');await health()}catch(e){toast(`Could not load demo context: ${e.message}`)}}
async function runTick(){try{if(!state.demoLoaded)await loadDemo();const d=await request('/v1/tick',{method:'POST',body:JSON.stringify({now:new Date().toISOString(),available_triggers:[demoTrigger.id]})});const a=d.actions?.[0];if(a){appendVera(a.body||'Vera produced an action.',a.rationale);toast('Vera composed a grounded action.')}else toast('No action returned — trigger may be suppressed.')}catch(e){toast(`Tick failed: ${e.message}`)}}
async function sendReply(){const input=$('#replyInput');const msg=input.value.trim();if(!msg)return;appendMerchant(msg);input.value='';try{const d=await request('/v1/reply',{method:'POST',body:JSON.stringify({conversation_id:'conv_m_001_drmeera_dentist_delhi_trg_001_research_digest_dentists',merchant_id:demoMerchant.merchant_id,message:msg,from_role:'merchant',turn_number:3,received_at:new Date().toISOString()})});if(d.body)appendVera(d.body,d.rationale);else toast(`Vera action: ${d.action||'handled'}`)}catch(e){toast(`Reply failed: ${e.message}`)}}
function appendMerchant(text){const c=$('#chat');const row=document.createElement('div');row.className='message merchant';row.innerHTML=`<div><div class="bubble"></div><span class="msg-time">Merchant · now</span></div><div class="msg-avatar merchant-avatar">DM</div>`;row.querySelector('.bubble').textContent=text;c.appendChild(row);c.scrollTop=c.scrollHeight}
function appendVera(text,rationale=''){const c=$('#chat');const row=document.createElement('div');row.className='message vera';row.innerHTML=`<div class="msg-avatar">V</div><div><div class="bubble"></div><span class="msg-time">Vera · now</span></div>`;row.querySelector('.bubble').textContent=text;if(rationale){const s=document.createElement('div');s.className='source';s.textContent=rationale;row.querySelector('.bubble').appendChild(s)}c.appendChild(row);c.scrollTop=c.scrollHeight;$('#signalCount').textContent='13'}
function nav(){ $$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+btn.dataset.view).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(btn.dataset.view==='conversations')copyChatToLarge()}))}
function copyChatToLarge(){const dest=$('#chatLarge');if(!dest||dest.dataset.ready)return;dest.innerHTML=$('#chat').innerHTML;dest.dataset.ready='1'}
$('#healthBtn').onclick=health;$('#refreshBtn').onclick=health;$('#loadDemoBtn').onclick=loadDemo;$('#loadContextBtn').onclick=loadDemo;$('#tickBtn').onclick=runTick;$('#convTick').onclick=runTick;$('#replyBtn').onclick=sendReply;$('#replyInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendReply()});$('#saveApi').onclick=()=>{state.apiBase=$('#apiBase').value.trim().replace(/\/$/,'');localStorage.setItem('vera_api_base',state.apiBase);toast('Backend URL saved.');health()};$('#apiBase').value=state.apiBase;nav();health();
